### ISSUE TITLE
Create an extra Table for past games

### ISSUE THREAD

**Issue by LucaZwahlen** [sopra-fs22-group-13/braendi-dog-server#140]
- [x] Params: 4 FKs for the 4 users, winner, 4x marblesInGoal, date created
- [x] Should be created in the game: when it ends, (also when it closes? idk)
- [x] Add a function that retrieves all games for a user (with an SQL statement plz, dont loop over it in java)
- [x] Add the list of played games for a user to the rest mapping of userInfo

**Comment by Xyarlo** [comment]
8d9fbadfc937e0602b2795ccfa9b167ec0d223fc
