### ISSUE TITLE
Bugfixes in Move Validation

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#90]
- [x] getColorfromPosition doesnt work with starting moves, since -1 has no marble on the board
- [x] validation for goal move is wrong, get_fromPosInGoal() is never empty

**Comment by shzeng** [comment]
bugs fixed

**Comment by shzeng** [comment]
c381ef0cdeca8c7b1e0170717a9a9973ed9f6d95

**Comment by LucaZwahlen** [comment]
have you even tested this? a basic starting move still fails (eg: RED, King, -1, 0)
And EVERY move fails anyway since move.checkIfComplete is not negated.

**Comment by shzeng** [comment]
> have you even tested this? a basic starting move still fails (eg: RED, King, -1, 0) And EVERY move fails anyway since move.checkIfComplete is not negated.

should work now i think, still writing tests

**Comment by shzeng** [comment]
6b511ca32122d64b9dc62a33b3ee41db4595238e
